### PR TITLE
bugfix camera that was not working

### PR DESCRIPTION
**Pull request by Lotti**
https://stackoverflow.com/questions/11642926/stop-close-webcam-which-is-opened-by-navigator-getusermedia

### CODE REVIEW

**Comment by stefanopog** [comment]
I manually made the changes you proposed on my running code. They work perfectly. THANKS SO MUCH @Lotti

**Comment by Lotti** [comment]
I observed that the camera stays on (led is full green on my mac) and that the first photo taken is always full-white or full-color.. then the next one is fine. Maybe timing issues during videoplayer/canvas setup while the camera is being switched on?

Unfortunately I didn't find any solution about switching off camera :\

**Comment by stefanopog** [comment]
Valerio, for me this solved the issue completely. GRAZIE !

**Comment by jeancarl** [comment]
Thank you so much @Lotti for this update! It has been published to npm.

**Pull request merged**
